FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# tshchemistry

This is examplde API to keep track of known elements and their properties

## Elements Collection [/elements]

### List All Elements [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Hydrogen",
                "atomicWeight": 1.008,
                "atomicNumber": 1,
                "group": 1,
                "period": 1,
                "finder": "Henry Cavendish"
            },
            {
                "id": 2,
                "name": "Helium",
                "atomicWeight": 4.002,
                "atomicNumber": 2,
                "group": 18,
                "period": 1,
                "finder": "Pierre Janssen"
            },
            {
                "id": 3,
                "name": "Lithium",
                "atomicWeight": 6.94,
                "atomicNumber": 3,
                "group": 1,
                "period": 2,
                "finder": "Johan August Arfwedson"
            }
        ]

### Create a New Element [POST]

If you have discovered new element, you can add it to periodic table using this endpoint.

+ Request (application/json)

        {
                "name": "Beryllium",
                "atomicWeight": 9.012,
                "atomicNumber": 4,
                "group": 2,
                "period": 2,
                "finder": "Louis Nicolas Vauquelin"
        }

+ Response 204

## Manage Elements [/elements/{id}]

+ Parameters 
    + id: 1
    

### Fetch single an Element [GET]

You need to get one element 

+ Response 200 (application/json)

        {
                "name": "Hydrogen",
                "atomicWeight": 4.002,
                "atomicNumber": 2,
                "group": 18,
                "period": 1,
                "finder": "Pierre Janssen"
        }
    

### Edit an Element [PUT]

There is a mistake in periodic table that needs to be fixed.

+ Request (application/json)

        {
                "name": "Hydrogen",
                "atomicWeight": 4.002,
                "atomicNumber": 2,
                "group": 18,
                "period": 1,
                "finder": "Pierre Janssen"
        }

+ Response 204 


### Delete an Element [DELETE]

+ Response 204